// <auto-generated />
using System;
using EventosWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventosWeb.Migrations
{
    [DbContext(typeof(EventosWebContext))]
    [Migration("20190223012428_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventosWeb.Models.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Cuando");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Lugar");

                    b.Property<int>("NDeInvitados");

                    b.Property<string>("Necesidad");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Cotizacion");
                });
#pragma warning restore 612, 618
        }
    }
}
